channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.10.5
  # - nodejs=18.7.0
  # - qt=5.15.4
  # - pyqt=5.15.7
  - pip=22.2.2

  - pip:
      # Define pip packages here.
      # https://pypi.org/
      # - pywebview[qt]==3.6.3
      - rpaframework==15.8.0 # https://rpaframework.org/releasenotes.html
      - robotframework==5.0.1
      # - robotframework-browser==12.4.0

# rccPostInstall:
  # - rfbrowser init